# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemNO', models.CharField(max_length=30, unique=True, verbose_name='\u7269\u53f7')),
                ('Name', models.CharField(max_length=200, verbose_name='\u540d\u79f0')),
                ('Material', models.FloatField(default=0, verbose_name='\u91cd\u91cf')),
            ],
        ),
    ]
