# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOMContent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part_Con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LNO', models.IntegerField(verbose_name='\u4ef6\u53f7')),
                ('LeefNum', models.IntegerField(verbose_name='\u5b50\u90e8\u4ef6\u6570\u91cf')),
                ('isWatch', models.BooleanField(default=False, verbose_name='\u8981\u6c42\u76d1\u89c6')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u5173\u7cfb',
                'verbose_name_plural': '\u4ea7\u54c1\u5173\u7cfb\u6c47\u603b',
            },
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': '\u4ea7\u54c1', 'verbose_name_plural': '\u4ea7\u54c1\u6c47\u603b'},
        ),
        migrations.RemoveField(
            model_name='part',
            name='Material',
        ),
        migrations.AddField(
            model_name='part',
            name='BelongedProNum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u539f\u5c5e\u4ea7\u54c1\u53f7'),
        ),
        migrations.AddField(
            model_name='part',
            name='DesignType',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8bbe\u8ba1\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='part',
            name='EName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u82f1\u6587\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='part',
            name='ManufactureRemark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5236\u9020\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='part',
            name='Mass',
            field=models.FloatField(blank=True, null=True, verbose_name='\u91cd\u91cf'),
        ),
        migrations.AddField(
            model_name='part',
            name='Matrial',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u6750\u6599'),
        ),
        migrations.AddField(
            model_name='part',
            name='Num',
            field=models.FloatField(blank=True, null=True, verbose_name='\u6570\u91cf'),
        ),
        migrations.AddField(
            model_name='part',
            name='Ratetime',
            field=models.DateField(blank=True, null=True, verbose_name='\u8003\u6838\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='part',
            name='Remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='part',
            name='StandardNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6807\u51c6\u53f7'),
        ),
        migrations.AddField(
            model_name='part',
            name='Unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8ba1\u91cf\u5355\u4f4d'),
        ),
        migrations.AddField(
            model_name='part',
            name='isFinish',
            field=models.BooleanField(default=False, verbose_name='\u5b8c\u6210'),
        ),
        migrations.AddField(
            model_name='part',
            name='isParts',
            field=models.BooleanField(default=False, verbose_name='\u90e8\u4ef6'),
        ),
        migrations.AddField(
            model_name='part',
            name='isProduct',
            field=models.BooleanField(default=False, verbose_name='\u4ea7\u54c1'),
        ),
        migrations.AddField(
            model_name='part_con',
            name='Head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HeadBJ', to='BOMContent.Part', verbose_name='\u4e3b\u90e8\u4ef6'),
        ),
        migrations.AddField(
            model_name='part_con',
            name='Leef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LeefBJ', to='BOMContent.Part', verbose_name='\u5b50\u90e8\u4ef6'),
        ),
    ]
