# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOMContent', '0002_auto_20171212_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='Num',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='part_con',
            name='Head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HeadBJ', to='BOMContent.Part', verbose_name='\u4e3b\u90e8\u4ef6'),
        ),
        migrations.AlterField(
            model_name='part_con',
            name='Leef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LeefBJ', to='BOMContent.Part', verbose_name='\u5b50\u90e8\u4ef6'),
        ),
    ]
